name: Init CI4

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Show Composer/PHP versions
        shell: bash
        run: |
          php -v
          composer -V

      - name: Create CodeIgniter 4 app in temp dir
        shell: bash
        run: composer create-project codeigniter4/appstarter app-tmp

      - name: Require dompdf inside temp app
        shell: bash
        working-directory: app-tmp
        run: composer require dompdf/dompdf:^2.0

      - name: Copy app files into repo (preserve .git)
        shell: bash
        run: |
          set -euo pipefail
          # Copy including dotfiles; the ". ." suffix is crucial
          cp -a app-tmp/. .
          rm -rf app-tmp

      - name: Generate app key and example env
        shell: bash
        run: |
          cp -n env .env || true
          php spark key:generate || true

      - name: Commit and push
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Initialize CodeIgniter 4 app with dompdf"
            git push
          fi
