name: Init CI4

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Create CI4 app in temp dir
        run: composer create-project codeigniter4/appstarter app-tmp

      - name: Require dompdf inside temp app
        working-directory: app-tmp
        run: composer require dompdf/dompdf:^2.0

      - name: Move app files to repo (preserve .git)
        run: |
          shopt -s dotglob
          rm -rf ./* || true
          shopt -u dotglob
          tar -C app-tmp -cf app.tar .
          tar -xf app.tar
          rm -rf app-tmp app.tar

      - name: Generate app key and example env
        run: |
          cp -n env .env || true
          php spark key:generate || true

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Initialize CodeIgniter 4 app with dompdf"
            git push
          fi
